CREATE TRIGGER AddProduct
ON Product
FOR INSERT
AS
BEGIN
DECLARE @NAME_PRODUCT NVARCHAR,
		@PRICE MONEY,
		@COST_PRICE MONEY,
		@QUANTITY INT,

		@NAME_PRODUCT_P NVARCHAR,
		@PRICE_P MONEY,
		@COST_PRICE_P MONEY,
		@QUANTITY_P INT



SELECT @NAME_PRODUCT = inserted.NAME_PRODUCT, @PRICE = inserted.[PRICE], @COST_PRICE = inserted.COST_PRICE, @QUANTITY = inserted.QUANTITY
FROM inserted

SELECT @QUANTITY_P = p.QUANTITY
FROM Product p
where p.NAME_PRODUCT = @NAME_PRODUCT

PRINT @QUANTITY_P
--SET @QUANTITY_P = Product.QUANTITY
	PRINT @QUANTITY
	

--IF (@NAME_PRODUCT = @NAME_PRODUCT_P AND @PRICE = @PRICE_P AND @COST_PRICE = @COST_PRICE_P)
--	UPDATE Product
--	SET QUANTITY = @QUANTITY_P+@QUANTITY
--	PRINT (@QUANTITY)
--	PRINT (@QUANTITY_P)
--	--PRINT (QUANTITY)
--	PRINT ('Изменено количество')
END

INSERT INTO Product ( NAME_PRODUCT, QUANTITY, COST_PRICE , PRICE, MANUFACTURERID, TYPE_OF_GOODSID) VALUES
('Кросовки', 62, 350, 450, 1, 3)


USE SportMagazine;
GO

CREATE TRIGGER Staff_Delete
ON Staff
AFTER DELETE
AS
INSERT INTO HistoryStaff (Position, Date_Of_Receipt, Salary)
SELECT Position, Date_Of_Receipt, Salary
FROM deleted
GO