CREATE DATABASE SportMagazine;
GO

USE SportMagazine;
GO

CREATE TABLE HistoryStaff
(
	ID	 	   			INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	POSITION			NVARCHAR(MAX) CHECK(POSITION	<>'') NOT NULL,
	DATE_OF_RECEIPT 	DATE CHECK(DATE_OF_RECEIPT <= GETDATE()) NOT NULL,
	SALARY		   		MONEY CHECK(SALARY > 0) NOT NULL,
	CREATE_AT		    DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Sex (
	ID	 	        INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	SEX				NVARCHAR(20) CHECK(SEX = 'MALE' OR SEX = 'FEMALE') NOT NULL
)
GO

CREATE TABLE Person (
	ID	 	        	INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME_PERSON  		NVARCHAR(MAX) CHECK(NAME_PERSON	<>'') NOT NULL,
	SURNAME_PERSON		NVARCHAR(MAX) CHECK(SURNAME_PERSON	<>'') NOT NULL,
	PATRONYMIC_PERSON	NVARCHAR(MAX) CHECK(PATRONYMIC_PERSON	<>'') NOT NULL,
	SEXID 				INT NOT NULL REFERENCES Sex (Id)
)
GO

CREATE TABLE Staff (
	ID	 	   			INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	POSITION			NVARCHAR(MAX) CHECK(POSITION	<>'') NOT NULL,
	DATE_OF_RECEIPT 	DATE CHECK(DATE_OF_RECEIPT<=CONVERT(date, getdate())) NOT NULL,
	SALARY		   		MONEY CHECK(SALARY > 0) NOT NULL,
	PERSONID 			INT NOT NULL REFERENCES Person (Id)
)
GO

CREATE TABLE Client (
	ID	 	        	INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	EMAIL 				NVARCHAR(MAX) CHECK(EMAIL	<>'') NOT NULL,
	TELEPHONE			INT CHECK(TELEPHONE	<>'') NOT NULL,
	DISCOUNT			INT CHECK(DISCOUNT >= 0 AND DISCOUNT <=100) NOT NULL,
	MAILING_LIST		NVARCHAR(20) CHECK(MAILING_LIST = 'YES' OR MAILING_LIST = 'NO') NOT NULL,
	DOR 				DATE CHECK(DOR <=CONVERT(date, getdate())) NOT NULL,
	PERSONID 			INT NOT NULL REFERENCES Person (Id)
)
GO

CREATE TABLE Manufacturer (
	ID	 	        INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MANUFACTURER	NVARCHAR(50) CHECK(MANUFACTURER <>'') UNIQUE NOT NULL
)
GO

CREATE TABLE TypeOfGoods (
	ID	 	        INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TYPE_OF_GOODS	NVARCHAR(50) CHECK(TYPE_OF_GOODS <>'') UNIQUE NOT NULL
)
GO

CREATE TABLE Product (
	ID	 		    INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME_PRODUCT	NVARCHAR(MAX) CHECK(NAME_PRODUCT <>'') NOT NULL,
	QUANTITY		INT CHECK(QUANTITY >= 0) NOT NULL,
	COST_PRICE  	MONEY CHECK(COST_PRICE > 0) NOT NULL,
	PRICE			MONEY CHECK(PRICE > 0) NOT NULL,
	MANUFACTURERID  INT NOT NULL REFERENCES Manufacturer (Id),
	TYPE_OF_GOODSID INT NOT NULL REFERENCES TypeOfGoods (Id)
)
GO

CREATE TABLE Sale (
	ID	 	        	INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	QUANTITY_SALE		INT CHECK(QUANTITY_SALE > 0) NOT NULL,
	DATE_OF_SALE	 	DATE CHECK(DATE_OF_SALE>=CONVERT(date, getdate())) NOT NULL,
	SELLING_PRICE		MONEY CHECK(SELLING_PRICE > 0) NOT NULL,
	PRODUCTID		    INT NOT NULL REFERENCES Product (Id),
	CLIENTID	 		INT NOT NULL REFERENCES Client (Id),
	STAFFID  			INT NOT NULL REFERENCES Staff (Id)
)
GO



INSERT INTO Sex (SEX) VALUES
('MALE'),
('FEMALE'),
('MALE'),
('FEMALE'),
('MALE');

INSERT INTO Person ( NAME_PERSON, SURNAME_PERSON, PATRONYMIC_PERSON, SEXID) VALUES
('Andrey', 'Yaroslavskey', 'Borisovich',1),
('Andrey', 'Mashkovskiy', 'Batkovich',3),
('Danila', 'Yaroslavskey', 'Andreevich',5),
('Tamara', 'Petrova', 'Ivanovna',4),
('Irina', 'Ivanova', 'Nikolaevna',2);

INSERT INTO Staff ( POSITION, DATE_OF_RECEIPT, SALARY, PERSONID) VALUES
('Кладовщик', '2004-05-05', 10200,1),
('Директор', '2010-06-15', 25000,3),
('Специалист по охране труда', '2015-01-18', 8300,2),
('Охранник', '2020-11-03', 3500,5),
('Кладовщик', '2021-02-05', 10200,4);

INSERT INTO Client ( DOR, EMAIL, TELEPHONE, DISCOUNT, MAILING_LIST, PERSONID) VALUES
('2004-05-05','yaroslavskey@ukr.net', 0994962513, 50, 'YES', 1),
('2010-06-15','ads@ukr.net', 0675861235, 25,'YES',3),
('2015-01-18','hanter@ukr.net', 0678562315, 0, 'YES', 2),
('2020-11-03','batman@mail.ru', 0684962513, 10, 'NO', 5),
('2021-02-05','qwert@rambler.ru', 0997456213, 5, 'NO', 4);

INSERT INTO Manufacturer (MANUFACTURER) VALUES
('NIKE'),
('ADIDAS'),
('VASIL GYM'),
('PUMA'),
('HUMEL');

INSERT INTO TypeOfGoods (TYPE_OF_GOODS) VALUES
('Обувь'),
('Одежда'),
('Мячи'),
('Спортивное питание'),
('Тренажеры');

INSERT INTO Product ( NAME_PRODUCT, QUANTITY, COST_PRICE , PRICE, MANUFACTURERID, TYPE_OF_GOODSID) VALUES
('Кросовки', 10, 350, 450, 1, 3),
('Гантели', 5, 1200, 1500, 2, 4),
('Мяч волейбольный', 3, 2500, 3200, 4, 5),
('Футболка', 20, 300, 450, 5, 2),
('Протеин', 30, 365, 425, 3, 1);

INSERT INTO Sale ( QUANTITY_SALE, DATE_OF_SALE, SELLING_PRICE, PRODUCTID, CLIENTID, STAFFID) VALUES
(2, '2022-05-20', 450, 1, 1, 3),
(1, '2022-03-20', 450, 2, 3, 2),
(3, '2022-06-19', 1200, 3, 2, 1),
(2, '2021-08-21', 250, 4, 5, 4),
(1, '2021-08-22', 450, 5, 4, 5);