
--создание БД
CREATE DATABASE Academy 

--удаление БД
DROP DATABASE Academy 


--создание таблиц

CREATE TABLE Curators (
	ID	 	    INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME		NVARCHAR(MAX) CHECK(NAME <>'') NOT NULL,
	SURNAME		NVARCHAR(MAX) CHECK(SURNAME <>'') NOT NULL
)
GO

CREATE TABLE Departments (
	ID		    INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FINANCING	MONEY CHECK(FINANCING >= 0) DEFAULT 0 NOT NULL,
	NAME		NVARCHAR(100) CHECK(NAME <>'') UNIQUE NOT NULL,
	FACULTYID	INT  NOT NULL,
)
GO

CREATE TABLE Faculties (
	ID		    INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME		NVARCHAR(100) CHECK(NAME <>'') UNIQUE NOT NULL,
	FINANCING	MONEY CHECK(FINANCING >= 0) DEFAULT 0 NOT NULL
)
GO

CREATE TABLE Groups (
	ID	         INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME	     NVARCHAR(10) CHECK(NAME <>'') UNIQUE NOT NULL,
	YEARS        INT CHECK(YEARS >= 1 AND YEARS <= 5) NOT NULL,
	DEPARTMENTID INT NOT NULL
)
GO

CREATE TABLE GroupsCurators (
	ID	         INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CURATORID    INT  NOT NULL,
	GROUPID	     INT  NOT NULL
)
GO

CREATE TABLE GroupsLectures (
	ID	         INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	LECTUREID    INT NOT NULL,
	GROUPID	     INT NOT NULL
)
GO

CREATE TABLE Lectures (
	ID	         INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	LECTUREROOM  NVARCHAR(MAX) CHECK(LECTUREROOM <>'') NOT NULL,
	SUBJECTID    INT NOT NULL,
	TEACHERID    INT NOT NULL
)
GO


CREATE TABLE Subjects (
	ID	 	    INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME		NVARCHAR(100) CHECK(NAME <>'') UNIQUE NOT NULL
)
GO


CREATE TABLE Teachers (
	ID	    INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME        NVARCHAR(MAX) CHECK(NAME <>'') NOT NULL,
	SURNAME	    NVARCHAR(MAX) CHECK(SURNAME <>'') NOT NULL,
	SALARY	    MONEY CHECK(SALARY > 0) NOT NULL
)
GO



